version: '3.4'

services:
  # app: 
  #   build: .
  #   command: npm run start
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - db
  db:
    container_name: 'database-node'
    image: postgres:15.1-alpine
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bossabox
    volumes: 
      - db:/var/lib/postgres/data
volumes:
  db:
    driver: local